# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class DataPipeline(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, filename=None):  # noqa: E501
        """DataPipeline - a model defined in OpenAPI

        :param filename: The filename of this DataPipeline.  # noqa: E501
        :type filename: List[file]
        """
        self.openapi_types = {
            'filename': List[file]
        }

        self.attribute_map = {
            'filename': 'filename'
        }

        self._filename = filename

    @classmethod
    def from_dict(cls, dikt) -> 'DataPipeline':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataPipeline of this DataPipeline.  # noqa: E501
        :rtype: DataPipeline
        """
        return util.deserialize_model(dikt, cls)

    @property
    def filename(self):
        """Gets the filename of this DataPipeline.


        :return: The filename of this DataPipeline.
        :rtype: List[file]
        """
        return self._filename

    @filename.setter
    def filename(self, filename):
        """Sets the filename of this DataPipeline.


        :param filename: The filename of this DataPipeline.
        :type filename: List[file]
        """

        self._filename = filename
